#!/bin/bash
[ "$CI_ENV" = yes ] && set -x
# interfaces:
#  - normal dtgilles/sshgw
#  - you should set user shell to "/usr/local/bin/script_login"

getlogfile()
   {
      for logfile in $(find /tmp/*_scriptlog -user ${owner:-root} -print)
         do
            [ -p "$logfile"     ] || continue
            [ -w "$logfile"     ] || continue
            [ -f "$logfile.pid" ] && continue
            touch "$logfile.time" || return 1
            echo $$ $login_user > "$logfile.pid" \
            && chmod 0600         "$logfile.pid" \
            && return 0
         done
      return 1
   }

while [ $# -gt 0 ]
   do
      case "$1"
         in
            -c) shift;;
            -u) readonly login_user="$2"; shift 2;;
            -o) readonly owner="$2";      shift 2;;
            *)  break;;
         esac
   done

##### wait until there is a logfile for me
while ! getlogfile; do printf .; sleep 10;done

if [ "$SSH_ORIGINAL_COMMAND" = "" ]
   then
      command=bash
   else
      command="bash -c '$SSH_ORIGINAL_COMMAND'"
   fi
script --timing="$logfile.time" -e -q -c "$command" "$logfile"
exit $?
